name: Node.js CICD

on:
  
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  cicd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: userapi
    steps:
      - uses: checkout
      - name: Use node.js
        uses: setup-node
        with:
          node-version: '16'
      - run: npm install
      - run: sudo apt-get install redis
      - run: sudo service redis-server start
      - run: npm test


